// SoyJordan Picks V2.5.0 build 2500 · Base Histórica SoyJordan
// IndexedDB canonical historical dataset + LocalStorage fallback/migration bridge.
(function(){
'use strict';

const HCFG={dbName:'SoyJordanHistoricalV2500',dbVersion:1,matchStore:'matches',betStore:'bets',resultStore:'results',metaStore:'meta',fallbackKey:'sjHistoricalFallbackV2500',pageSize:50,schemaVersion:1,modelVersion:'SoyJordan_V2_build2500',lambdaEngine:'lambda_v2500',selectorVersion:'selector_v2500',calibrationVersion:'calibration_v2500'};
const deep=v=>v==null?v:JSON.parse(JSON.stringify(v));
const n=(v,f=null)=>{if(v===null||v===undefined||v==='')return f;const x=Number(v);return Number.isFinite(x)?x:f};
const iso=()=>new Date().toISOString();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtPct=v=>Number.isFinite(v)?`${(v*100).toFixed(1)}%`:'—';
const fmtNum=(v,d=2)=>Number.isFinite(v)?Number(v).toFixed(d):'—';
const fmtMoney=v=>Number.isFinite(v)?money(v):'—';
const nullify=v=>v===undefined||v===''?null:v;
const dateKey=v=>String(v||'').replace(/-/g,'').slice(0,8)||new Date().toISOString().slice(0,10).replace(/-/g,'');
const statusEs=s=>({pending:'PENDIENTE',win:'GANADA',loss:'PERDIDA',push:'PUSH',half_win:'HALF WIN',half_loss:'HALF LOSS',void:'VOID'}[s]||String(s||'—').toUpperCase());

let dbPromise=null;
function openDB(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{
  if(typeof indexedDB==='undefined'||!indexedDB?.open)return resolve(null);
  const req=indexedDB.open(HCFG.dbName,HCFG.dbVersion);
  req.onupgradeneeded=()=>{const db=req.result;
    if(!db.objectStoreNames.contains(HCFG.matchStore)){const s=db.createObjectStore(HCFG.matchStore,{keyPath:'matchId'});s.createIndex('date','date');s.createIndex('league','league');s.createIndex('modelVersion','modelVersion');}
    if(!db.objectStoreNames.contains(HCFG.betStore)){const s=db.createObjectStore(HCFG.betStore,{keyPath:'betId'});s.createIndex('matchId','matchId');s.createIndex('status','status');s.createIndex('market','market');s.createIndex('modelVersion','modelVersion');}
    if(!db.objectStoreNames.contains(HCFG.resultStore)){const s=db.createObjectStore(HCFG.resultStore,{keyPath:'matchId'});s.createIndex('settledAt','settledAt');}
    if(!db.objectStoreNames.contains(HCFG.metaStore))db.createObjectStore(HCFG.metaStore,{keyPath:'key'});
  };
  req.onsuccess=()=>resolve(req.result);req.onerror=()=>{dbPromise=null;reject(req.error)};
});return dbPromise;}
async function idbPut(store,value){const db=await openDB();if(!db)return fallbackPut(store,value);return new Promise((res,rej)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(deep(value));tx.oncomplete=()=>res(value);tx.onerror=()=>rej(tx.error);});}

async function idbPutMany(store,values){const db=await openDB();if(!db){const d=fallbackLoad();d[store]=d[store]||[];const key=store===HCFG.betStore?'betId':store===HCFG.metaStore?'key':'matchId';const map=new Map(d[store].map(x=>[x[key],x]));(values||[]).forEach(v=>map.set(v[key],deep(v)));d[store]=[...map.values()];localStorage.setItem(HCFG.fallbackKey,JSON.stringify(d));return values;}return new Promise((res,rej)=>{const tx=db.transaction(store,'readwrite'),os=tx.objectStore(store);(values||[]).forEach(v=>os.put(deep(v)));tx.oncomplete=()=>res(values);tx.onerror=()=>rej(tx.error);});}
async function idbAll(store){const db=await openDB();if(!db)return fallbackAll(store);return new Promise((res,rej)=>{const tx=db.transaction(store,'readonly'),q=tx.objectStore(store).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error);});}
async function idbGet(store,key){const db=await openDB();if(!db){const rows=await fallbackAll(store);return rows.find(x=>(x.matchId||x.betId||x.key)===key)||null;}return new Promise((res,rej)=>{const tx=db.transaction(store,'readonly'),q=tx.objectStore(store).get(key);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error);});}
function fallbackLoad(){try{return JSON.parse(localStorage.getItem(HCFG.fallbackKey)||'{}')}catch{return {}}}
function fallbackPut(store,value){const d=fallbackLoad();d[store]=d[store]||[];const key=store===HCFG.betStore?'betId':store===HCFG.metaStore?'key':'matchId';const i=d[store].findIndex(x=>x[key]===value[key]);if(i>=0)d[store][i]=deep(value);else d[store].push(deep(value));localStorage.setItem(HCFG.fallbackKey,JSON.stringify(d));return Promise.resolve(value)}
function fallbackAll(store){return Promise.resolve(fallbackLoad()[store]||[])}
async function metaGet(key){return (await idbGet(HCFG.metaStore,key))?.value??null}
async function metaSet(key,value){return idbPut(HCFG.metaStore,{key,value,updatedAt:iso()})}

function modelVersionOf(r){return r?.modelVersion||((r?.build||r?.version)?`SoyJordan_V${r.version||'2'}_build${r.build||String(r.version||'').replace(/\D/g,'')||'legacy'}`:'SoyJordan_legacy')}
function seqId(prefix,date,existing){const dk=dateKey(date),re=new RegExp(`^SJ-${prefix}-${dk}-(\\d{4})$`),max=existing.reduce((m,x)=>{const v=String(prefix==='M'?x.matchId:x.betId||'').match(re);return v?Math.max(m,Number(v[1])):m},0);return `SJ-${prefix}-${dk}-${String(max+1).padStart(4,'0')}`}
function weightedCandidate(rows){const a=(rows||[]).slice().sort((x,y)=>(n(y.rankScore,n(y.vs,0)))-(n(x.rankScore,n(x.vs,0))));return a[0]||null}
function topSelected(r){try{return typeof getTopGeneral==='function'?getTopGeneral(r):null}catch{return null}}
function candidateSnapshot(row){if(!row)return null;return {market:row.market,label:typeof marketLabel==='function'?marketLabel(row.market):row.market,probability:n(row.p),oddsAvailable:n(row.odds),fairOdds:n(row.fair),marketFairProb:n(row.marketFairProb),edge:n(row.ed),ev:n(row.e),worstEV:n(row.worstEV),robustness:n(row.robustness),confidence:n(row.conf),score:n(row.rankScore,n(row.vs)),coherence:n(row.coherence),decision:row.dec||null,rejectReason:row.dec==='NO BET'?'No supera uno o más filtros de elegibilidad/robustez':null};}
function lambdaAudit(r){const d=r?.diagnostics||{};return {
  rawHome:n(d.rawH,n(d.structuralH)),rawAway:n(d.rawA,n(d.structuralA)),regularizedHome:n(d.regularizedH),regularizedAway:n(d.regularizedA),
  confirmationHome:n(d.confirmationHome?.factor,n(d.confirmFactorH,1)),confirmationAway:n(d.confirmationAway?.factor,n(d.confirmFactorA,1)),
  oppositionHome:n(d.oppFactorH,n(d.oppositionH?.attack,1)),oppositionAway:n(d.oppFactorA,n(d.oppositionA?.attack,1)),
  teamLevelHome:n(d.teamLevelFactorH,n(d.levelFactorH,1)),teamLevelAway:n(d.teamLevelFactorA,n(d.levelFactorA,1)),
  leagueLevelHome:n(d.interFactorH,1),leagueLevelAway:n(d.interFactorA,1),venueHome:n(d.venueFactorH,n(d.venueH,1)),venueAway:n(d.venueFactorA,n(d.venueA,1)),
  trendHome:n(d.trendFactorH,n(d.trendH?.globalFactor,1)),trendAway:n(d.trendFactorA,n(d.trendA?.globalFactor,1)),
  absenceHome:n(d.absenceHAtt,1),absenceAway:n(d.absenceAAtt,1),restHome:n(d.restH,1),restAway:n(d.restA,1),finalHome:n(r?.hl),finalAway:n(r?.al),total:(n(r?.hl)!=null&&n(r?.al)!=null)?n(r.hl)+n(r.al):null
};}
function probabilitiesOf(r){const out={};(r?.rows||[]).forEach(x=>{out[x.market]={probability:n(x.p),fairOdds:n(x.fair),oddsAvailable:n(x.odds),marketFairProb:n(x.marketFairProb),ev:n(x.e),worstEV:n(x.worstEV)};});return out}
function absAgg(r,side){const base=r?.absenceImpact?.[side]||{}, adv=r?.absenceAdvanced?.[side]||r?.absenceContext?.[side]||{};return {grossAttack:n(adv.grossAttack,n(base.att)),grossDefense:n(adv.grossDefense,n(base.def)),participation:n(adv.participation),tacticalWeight:n(adv.tacticalWeight),replacementQuality:n(adv.replacementQuality),certainty:n(adv.certainty),historicalAbsorption:n(adv.historicalAbsorption),effectiveAttack:n(adv.effectiveAttack,n(base.att)),effectiveDefense:n(adv.effectiveDefense,n(base.def)),players:deep(r?.absences?.[side]||[])};}
function makePreMatchSnapshot(r){const selected=topSelected(r),cand=weightedCandidate(r?.rows),top=selected||cand;return {
  schemaVersion:HCFG.schemaVersion,modelVersion:modelVersionOf(r),build:n(r?.build),lambdaEngine:r?.lambdaEngineVersion||HCFG.lambdaEngine,selectorVersion:r?.selectorVersion||HCFG.selectorVersion,calibrationVersion:r?.calibrationVersion||HCFG.calibrationVersion,
  frozenAt:iso(),identification:{date:r?.date||null,time:r?.time||null,league:r?.league||null,country:r?.country||null,competition:r?.competition||r?.league||null,mode:r?.matchMode||'league',round:r?.cupContext?.stage||r?.round||null,home:r?.home||null,away:r?.away||null},
  inputs:{season:r?.season||null,leagueAvg:n(r?.leagueAvg),homeLeagueAvg:n(r?.homeLeagueAvg),awayLeagueAvg:n(r?.awayLeagueAvg),homeLeagueStrength:n(r?.homeLeagueStrength),awayLeagueStrength:n(r?.awayLeagueStrength),homeTeamStrength:n(r?.homeTeamStrength),awayTeamStrength:n(r?.awayTeamStrength),teams:deep(r?.teams||{}),absences:{home:absAgg(r,'home'),away:absAgg(r,'away')},odds:deep(r?.odds||{}),europeanHandicapOdds:deep(r?.eh||{}),dataSource:r?.dataSource||null,notes:r?.notes||null,cupContext:deep(r?.cupContext||null)},
  lambda:lambdaAudit(r),probabilities:probabilitiesOf(r),candidates:(r?.rows||[]).slice().sort((a,b)=>n(b.rankScore,n(b.vs,0))-n(a.rankScore,n(a.vs,0))).slice(0,3).map(candidateSnapshot),
  selector:{topCandidate:candidateSnapshot(cand),selected:candidateSnapshot(selected),decision:selected?'BET':'NO BET',noBetReason:selected?null:(cand?.dec==='NO BET'?'El mejor candidato no superó los filtros finales':'Sin candidato elegible')},dataConfidence:n(r?.dataConfidence)
};}
function normalizeMatch(r,existing=[]){
  if(!r.matchId)r.matchId=seqId('M',r.date,existing);if(!r.createdAt)r.createdAt=r.analyzedAt||new Date(n(r.id,Date.now())).toISOString();if(!r.analyzedAt)r.analyzedAt=r.createdAt;if(!r.modelVersion)r.modelVersion=modelVersionOf(r);r.updatedAt=r.updatedAt||iso();
  if(!r.preMatchSnapshot)r.preMatchSnapshot=makePreMatchSnapshot(r);
  const s=deep(r.preMatchSnapshot),sel=s?.selector?.selected,top=s?.selector?.topCandidate;
  return {matchId:r.matchId,legacyAnalysisId:r.id??null,date:r.date||null,time:r.time||null,league:r.league||null,country:r.country||null,competition:r.competition||r.league||null,mode:r.matchMode||'league',round:r.cupContext?.stage||null,home:r.home||null,away:r.away||null,modelVersion:r.modelVersion,build:n(r.build),lambdaEngine:r.lambdaEngineVersion||HCFG.lambdaEngine,selectorVersion:r.selectorVersion||HCFG.selectorVersion,calibrationVersion:r.calibrationVersion||HCFG.calibrationVersion,createdAt:r.createdAt,analyzedAt:r.analyzedAt,updatedAt:r.updatedAt,lockedAt:r.lockedAt||null,status:r.realResult?'FINALIZADO':r.preMatchLocked?'PREPARTIDO BLOQUEADO':'ANALIZADO',preMatchSnapshot:s,levelHome:n(s?.inputs?.homeTeamStrength),levelAway:n(s?.inputs?.awayTeamStrength),lambdaHome:n(s?.lambda?.finalHome),lambdaAway:n(s?.lambda?.finalAway),lambdaTotal:n(s?.lambda?.total),topPick:(sel||top)?.label||'NO BET',topMarket:(sel||top)?.market||null,topDecision:s?.selector?.decision||'NO BET',probability:n((sel||top)?.probability),oddsAvailable:n((sel||top)?.oddsAvailable),ev:n((sel||top)?.ev),worstEV:n((sel||top)?.worstEV),robustness:n((sel||top)?.robustness),confidence:n((sel||top)?.confidence),score:n((sel||top)?.score),suggestedStakePct:n((sel||top)?.stakePct),noBetReason:s?.selector?.noBetReason||null,candidates:deep(s?.candidates||[]),notes:r.notes||null};
}
function normalizeBet(b,r,existing=[]){
  if(!b.betId)b.betId=seqId('B',b.date||r?.date,existing);if(!b.matchId)b.matchId=r?.matchId||null;if(!b.betRegisteredAt)b.betRegisteredAt=b.createdAt||iso();if(!b.createdAt)b.createdAt=b.betRegisteredAt;if(!b.updatedAt)b.updatedAt=iso();
  const snap=deep(b.preMatchSnapshot&&b.preMatchSnapshot.inputs?b.preMatchSnapshot:r?.preMatchSnapshot||b.preMatchSnapshot||null);if(!b.preMatchSnapshotFrozen&&snap)b.preMatchSnapshotFrozen=snap;
  const row=(r?.rows||[]).find(x=>String(x.market)===String(b.market)),rs= row?candidateSnapshot(row):null,ps=b.preMatchSnapshotFrozen;
  const p=n(b.preMatchSnapshot?.prob,n(rs?.probability,n(ps?.selector?.selected?.probability,n(ps?.selector?.topCandidate?.probability))));const close=n(b.closingOdds,n(b.closeOdds));const clv=close!=null&&close>1&&n(b.odds)>1?n(b.odds)/close-1:null;const binary=['win','loss'].includes(b.status);const brier=binary&&p!=null?(p-(b.status==='win'?1:0))**2:null;
  return {betId:b.betId,legacyBetId:b.id??null,matchId:b.matchId,legacyAnalysisId:b.analysisId??null,date:b.date||r?.date||null,league:r?.league||null,country:r?.country||null,mode:r?.matchMode||'league',match:`${b.home||r?.home||''} vs ${b.away||r?.away||''}`,home:b.home||r?.home||null,away:b.away||r?.away||null,market:b.market||null,selection:b.label||rs?.label||null,oddsAvailable:n(rs?.oddsAvailable),oddsSelected:n(rs?.oddsAvailable),oddsTaken:n(b.odds),closingOdds:close,modelProbability:p,marketFairProbability:n(b.preMatchSnapshot?.marketFairProb,n(rs?.marketFairProb)),edge:n(rs?.edge),ev:n(b.preMatchSnapshot?.ev,n(rs?.ev)),worstEV:n(b.preMatchSnapshot?.worstEV,n(rs?.worstEV)),robustness:n(b.preMatchSnapshot?.robustness,n(rs?.robustness)),confidence:n(b.preMatchSnapshot?.confidence,n(rs?.confidence)),score:n(b.preMatchSnapshot?.score,n(rs?.score)),stakePct:n(b.stakePct,n(b.units)!=null?n(b.units)/100:null),stakeAmount:n(b.stake),isFreeBet:!!(b.isFreeBet||b.betType==='freebet'),status:b.status||'pending',pnl:n(b.pnl,0),clv,brier,modelVersion:r?.modelVersion||modelVersionOf(r),betRegisteredAt:b.betRegisteredAt,settledAt:b.settledAt||null,updatedAt:b.updatedAt,preMatchSnapshot:deep(b.preMatchSnapshotFrozen||snap),notes:b.notes||null,comboIds:(typeof loadCombos==='function'?loadCombos():[]).filter(c=>(c.legs||[]).some(l=>String(l.analysisId)===String(b.analysisId)&&String(l.market)===String(b.market))).map(c=>c.id),auditLog:deep(b.auditLog||[])};
}
function normalizeResult(r){if(!r?.realResult||!r.matchId)return null;const rr=r.realResult,lh=n(r.preMatchSnapshot?.lambda?.finalHome,n(r.hl)),la=n(r.preMatchSnapshot?.lambda?.finalAway,n(r.al)),hg=n(rr.homeGoals),ag=n(rr.awayGoals);return {matchId:r.matchId,legacyAnalysisId:r.id??null,homeGoals:hg,awayGoals:ag,totalGoals:hg!=null&&ag!=null?hg+ag:null,homeXg:n(rr.homeXg),awayXg:n(rr.awayXg),homeShots:n(rr.homeShots),awayShots:n(rr.awayShots),homeSot:n(rr.homeSot),awaySot:n(rr.awaySot),homeBigChances:n(rr.homeBigChances),awayBigChances:n(rr.awayBigChances),lambdaErrorHome:hg!=null&&lh!=null?hg-lh:null,lambdaErrorAway:ag!=null&&la!=null?ag-la:null,lambdaErrorTotal:hg!=null&&ag!=null&&lh!=null&&la!=null?(hg+ag)-(lh+la):null,recordedAt:rr.recordedAt||iso(),settledAt:rr.recordedAt||iso(),updatedAt:iso(),notes:rr.notes||null};}

let syncing=false;
async function syncAll(){if(syncing)return;syncing=true;try{
  const analyses=loadDB(),bets=loadBets();const storedMatches=await idbAll(HCFG.matchStore),storedBets=await idbAll(HCFG.betStore);
  let changedA=false,changedB=false;
  for(const r of analyses){const before=JSON.stringify([r.matchId,r.createdAt,r.analyzedAt,r.modelVersion,!!r.preMatchSnapshot]);normalizeMatch(r,[...storedMatches,...analyses]);if(before!==JSON.stringify([r.matchId,r.createdAt,r.analyzedAt,r.modelVersion,!!r.preMatchSnapshot]))changedA=true;}
  const map=new Map(analyses.map(r=>[String(r.id),r]));for(const b of bets){const r=map.get(String(b.analysisId));const before=JSON.stringify([b.betId,b.matchId,b.betRegisteredAt,!!b.preMatchSnapshotFrozen]);normalizeBet(b,r,[...storedBets,...bets]);if(before!==JSON.stringify([b.betId,b.matchId,b.betRegisteredAt,!!b.preMatchSnapshotFrozen]))changedB=true;}
  if(changedA)localStorage.setItem('valuePickDB',JSON.stringify(analyses));if(changedB)localStorage.setItem('sjBetsV161',JSON.stringify(bets));
  const matchRows=[],resultRows=[],betRows=[];for(const r of analyses){matchRows.push(normalizeMatch(r,[...storedMatches,...analyses]));const rr=normalizeResult(r);if(rr)resultRows.push(rr);}for(const b of bets){const r=map.get(String(b.analysisId));if(r)betRows.push(normalizeBet(b,r,[...storedBets,...bets]));}
  await Promise.all([idbPutMany(HCFG.matchStore,matchRows),idbPutMany(HCFG.resultStore,resultRows),idbPutMany(HCFG.betStore,betRows)]);
  await metaSet('schemaVersion',HCFG.schemaVersion);await metaSet('lastSyncAt',iso());
 }catch(e){console.error('Base Histórica: error de sincronización',e)}finally{syncing=false;}}
window.SoyJordanHistorical={config:HCFG,syncAll,allMatches:()=>idbAll(HCFG.matchStore),allBets:()=>idbAll(HCFG.betStore),allResults:()=>idbAll(HCFG.resultStore),metaGet,metaSet};

// Hooks: preserve existing app behavior, enrich synchronously, then mirror asynchronously.
const _saveDB=window.saveDB;window.saveDB=function(x){
  const stored=(x||[]);stored.forEach(r=>{r.updatedAt=iso();r.lambdaEngineVersion=r.lambdaEngineVersion||HCFG.lambdaEngine;r.selectorVersion=r.selectorVersion||HCFG.selectorVersion;r.calibrationVersion=r.calibrationVersion||HCFG.calibrationVersion;normalizeMatch(r,stored)});
  const out=_saveDB(stored);setTimeout(syncAll,0);return out;
};
const _saveBets=window.saveBets;window.saveBets=function(x){
  const arr=x||[], analyses=loadDB();
  arr.forEach(b=>{b.updatedAt=iso();const r=analyses.find(a=>String(a.id)===String(b.analysisId));normalizeBet(b,r,arr);});
  const out=_saveBets(arr);setTimeout(syncAll,0);return out;
};
const _saveCombos=window.saveCombos;window.saveCombos=function(x){const out=_saveCombos(x);setTimeout(syncAll,0);return out};

let state={view:'matches',page:1,filters:{}};
function injectUI(){const cal=document.getElementById('calibration');if(!cal||document.getElementById('historicalBase'))return;const host=cal.querySelector('.card');if(!host)return;
  const tabs=document.createElement('div');tabs.className='cal-main-tabs';tabs.innerHTML='<button type="button" class="cal-main-tab active" data-cal-main="summary">Resumen / Calibración</button><button type="button" class="cal-main-tab secondary" data-cal-main="historical">🗃️ Base Histórica SoyJordan</button>';host.insertBefore(tabs,host.children[1]||null);
  const base=document.createElement('div');base.id='historicalBase';base.className='hidden';base.innerHTML=`
    <div class="historical-head"><div><h2>🗃️ BASE HISTÓRICA SOYJORDAN</h2><p class="small muted">Dataset histórico del modelo. Prepartido y postpartido permanecen separados para prevenir data leakage y look-ahead bias.</p></div><div class="historical-actions"><button type="button" id="histSearchBtn">Buscar</button><button type="button" class="secondary" id="histFilterBtn">Filtrar</button><button type="button" class="secondary" id="histColumnsBtn">Columnas</button><button type="button" class="secondary" id="histExportBtn">Exportar</button></div></div>
    <div id="histHealth"></div><div class="hist-view-tabs"><button data-hv="matches" class="active">Partidos</button><button data-hv="bets" class="secondary">Apuestas</button><button data-hv="results" class="secondary">Resultados</button><button data-hv="builds" class="secondary">Comparar builds</button></div>
    <div id="histSearchPanel" class="hist-panel"><input id="histSearch" placeholder="Buscar equipo, partido, liga, ID, mercado o pick…"><button id="histSearchApply" type="button">Aplicar</button><button id="histSearchClear" type="button" class="secondary">Limpiar</button></div>
    <div id="histFilterPanel" class="hist-panel hidden"></div><div id="histFilteredSummary"></div><div id="histTable"></div><div id="histPager" class="hist-pager"></div><div id="histBackupNote" class="small muted"></div>`;
  host.appendChild(base);
  const normal=[...host.children].filter(x=>x!==tabs&&x!==base);normal.forEach(x=>x.dataset.calNormal='1');
  tabs.querySelectorAll('[data-cal-main]').forEach(b=>b.onclick=()=>{const hist=b.dataset.calMain==='historical';tabs.querySelectorAll('button').forEach(x=>{x.classList.toggle('active',x===b);x.classList.toggle('secondary',x!==b)});normal.forEach(x=>x.classList.toggle('hidden',hist));base.classList.toggle('hidden',!hist);if(hist)renderHistorical();});
  base.querySelectorAll('[data-hv]').forEach(b=>b.onclick=()=>{state.view=b.dataset.hv;state.page=1;base.querySelectorAll('[data-hv]').forEach(x=>{x.classList.toggle('active',x===b);x.classList.toggle('secondary',x!==b)});renderHistorical();});
  document.getElementById('histSearchBtn').onclick=()=>document.getElementById('histSearchPanel').classList.toggle('hidden');document.getElementById('histFilterBtn').onclick=()=>document.getElementById('histFilterPanel').classList.toggle('hidden');
  document.getElementById('histSearchApply').onclick=()=>{state.filters.q=document.getElementById('histSearch').value.trim();state.page=1;renderHistorical()};document.getElementById('histSearchClear').onclick=()=>{document.getElementById('histSearch').value='';state.filters.q='';state.page=1;renderHistorical()};
  document.getElementById('histExportBtn').onclick=showExportMenu;document.getElementById('histColumnsBtn').onclick=()=>alert('En iPhone la tabla usa scroll horizontal y mantiene solo columnas de auditoría principales. La ficha completa contiene todos los campos históricos.');
}
function filterPanelOptions(matches,bets){const leagues=[...new Set(matches.map(x=>x.league).filter(Boolean))].sort(),builds=[...new Set(matches.map(x=>x.modelVersion).filter(Boolean))].sort(),markets=[...new Set(bets.map(x=>x.market).filter(Boolean))].sort();const p=document.getElementById('histFilterPanel');if(!p)return;p.innerHTML=`<div class="hist-filter-grid">
<label>Desde<input id="hfFrom" type="date" value="${esc(state.filters.from||'')}"></label><label>Hasta<input id="hfTo" type="date" value="${esc(state.filters.to||'')}"></label><label>Liga<select id="hfLeague"><option value="">Todas</option>${leagues.map(x=>`<option ${state.filters.league===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label>País<input id="hfCountry" value="${esc(state.filters.country||'')}"></label><label>Equipo<input id="hfTeam" value="${esc(state.filters.team||'')}"></label><label>Modo<select id="hfMode"><option value="">Todos</option><option value="league" ${state.filters.mode==='league'?'selected':''}>Liga</option><option value="cup" ${state.filters.mode==='cup'?'selected':''}>Copa/Interliga</option></select></label>
<label>Mercado<select id="hfMarket"><option value="">Todos</option>${markets.map(x=>`<option value="${esc(x)}" ${state.filters.market===x?'selected':''}>${esc(typeof marketLabel==='function'?marketLabel(x):x)}</option>`).join('')}</select></label><label>Resultado<select id="hfResult"><option value="">Todos</option><option value="win">Ganada</option><option value="loss">Perdida</option><option value="push">Push</option><option value="pending">Pendiente</option></select></label><label>Build<select id="hfBuild"><option value="">Todas</option>${builds.map(x=>`<option ${state.filters.build===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label>CLV<select id="hfClv"><option value="">Todos</option><option value="pos">Positivo</option><option value="neg">Negativo</option><option value="missing">Sin dato</option></select></label>
<label>Prob. mín. %<input id="hfProb" type="number" min="0" max="100" value="${esc(state.filters.probMin??'')}"></label><label>EV mín. %<input id="hfEv" type="number" value="${esc(state.filters.evMin??'')}"></label><label>EV peor mín. %<input id="hfWorst" type="number" value="${esc(state.filters.worstMin??'')}"></label><label>Robustez mín.<input id="hfRob" type="number" min="0" max="100" value="${esc(state.filters.robMin??'')}"></label><label>Confianza mín.<input id="hfConf" type="number" min="0" max="100" value="${esc(state.filters.confMin??'')}"></label><label>Score mín.<input id="hfScore" type="number" min="0" max="100" value="${esc(state.filters.scoreMin??'')}"></label><label>Top/NO BET<select id="hfDecision"><option value="">Todos</option><option value="BET">Top Pick</option><option value="NO BET">NO BET</option></select></label>
</div><div class="actions"><button id="hfApply" type="button">Aplicar filtros</button><button id="hfClear" class="secondary" type="button">Limpiar filtros</button></div>`;
  document.getElementById('hfResult').value=state.filters.result||'';document.getElementById('hfClv').value=state.filters.clv||'';document.getElementById('hfDecision').value=state.filters.decision||'';
  document.getElementById('hfApply').onclick=()=>{state.filters={...state.filters,from:val('hfFrom'),to:val('hfTo'),league:val('hfLeague'),country:val('hfCountry'),team:val('hfTeam'),mode:val('hfMode'),market:val('hfMarket'),result:val('hfResult'),build:val('hfBuild'),clv:val('hfClv'),probMin:n(val('hfProb')),evMin:n(val('hfEv')),worstMin:n(val('hfWorst')),robMin:n(val('hfRob')),confMin:n(val('hfConf')),scoreMin:n(val('hfScore')),decision:val('hfDecision')};state.page=1;renderHistorical()};document.getElementById('hfClear').onclick=()=>{const q=state.filters.q||'';state.filters={q};state.page=1;renderHistorical()};
}
const val=id=>document.getElementById(id)?.value||'';
function pass(x,kind){const f=state.filters,q=String(f.q||'').toLowerCase();if(q&&!JSON.stringify([x.matchId,x.betId,x.league,x.home,x.away,x.match,x.market,x.selection,x.topPick]).toLowerCase().includes(q))return false;if(f.from&&String(x.date||'')<f.from)return false;if(f.to&&String(x.date||'')>f.to)return false;if(f.league&&x.league!==f.league)return false;if(f.country&&!String(x.country||'').toLowerCase().includes(f.country.toLowerCase()))return false;if(f.team&&!`${x.home||''} ${x.away||''} ${x.match||''}`.toLowerCase().includes(f.team.toLowerCase()))return false;if(f.mode&&x.mode!==f.mode)return false;if(f.build&&x.modelVersion!==f.build)return false;if(f.market&&kind==='bets'&&x.market!==f.market)return false;if(f.result&&kind==='bets'&&x.status!==f.result)return false;if(f.decision&&kind==='matches'&&x.topDecision!==f.decision)return false;
  if(f.clv&&kind==='bets'){if(f.clv==='pos'&&!(x.clv>0))return false;if(f.clv==='neg'&&!(x.clv<0))return false;if(f.clv==='missing'&&x.clv!=null)return false;}const p=n(x.modelProbability,n(x.probability));if(f.probMin!=null&&p!=null&&p*100<f.probMin)return false;const e=n(x.ev);if(f.evMin!=null&&e!=null&&e*100<f.evMin)return false;const w=n(x.worstEV);if(f.worstMin!=null&&w!=null&&w*100<f.worstMin)return false;if(f.robMin!=null&&n(x.robustness)!=null&&x.robustness<f.robMin)return false;if(f.confMin!=null&&n(x.confidence)!=null&&x.confidence<f.confMin)return false;if(f.scoreMin!=null&&n(x.score)!=null&&x.score<f.scoreMin)return false;return true;}
function statsFiltered(matches,bets,results){const sb=bets.filter(x=>pass(x,'bets')&&['win','loss','push'].includes(x.status)),cash=sb.filter(x=>!x.isFreeBet),stake=cash.reduce((s,x)=>s+(n(x.stakeAmount,0)||0),0),pnl=cash.reduce((s,x)=>s+(n(x.pnl,0)||0),0),dec=sb.filter(x=>['win','loss'].includes(x.status)),wins=dec.filter(x=>x.status==='win').length,ps=dec.map(x=>n(x.modelProbability)).filter(Number.isFinite),br=dec.map(x=>n(x.brier)).filter(Number.isFinite),cl=sb.map(x=>n(x.clv)).filter(Number.isFinite),gw=cash.filter(x=>x.pnl>0).reduce((s,x)=>s+x.pnl,0),gl=Math.abs(cash.filter(x=>x.pnl<0).reduce((s,x)=>s+x.pnl,0));return {n:sb.length,winRate:dec.length?wins/dec.length:null,roi:stake?pnl/stake:null,pnl,pred:ps.length?ps.reduce((a,b)=>a+b,0)/ps.length:null,ev:avgN(sb.map(x=>x.ev)),worst:avgN(sb.map(x=>x.worstEV)),rob:avgN(sb.map(x=>x.robustness)),brier:avgN(br),clv:avgN(cl),pf:gl?gw/gl:null};}
const avgN=a=>{const v=a.map(n).filter(Number.isFinite);return v.length?v.reduce((s,x)=>s+x,0)/v.length:null};
async function health(matches,bets,results){const pct=(a,b)=>b?`${(a/b*100).toFixed(0)}%`:'—',withXg=results.filter(x=>x.homeXg!=null&&x.awayXg!=null).length,withClose=bets.filter(x=>x.closingOdds!=null).length,withOpp=matches.filter(x=>{const t=x.preMatchSnapshot?.inputs?.teams;return t?.home?.opposition&&t?.away?.opposition}).length,withAbs=matches.filter(x=>x.preMatchSnapshot?.inputs?.absences?.home&&x.preMatchSnapshot?.inputs?.absences?.away).length,last=await metaGet('lastBackupAt');const el=document.getElementById('histHealth');if(el)el.innerHTML=`<div class="summary hist-health"><div class="box">Partidos<br><b>${matches.length}</b></div><div class="box">Apuestas<br><b>${bets.length}</b></div><div class="box">Resultados<br><b>${results.length}</b></div><div class="box">Con xG real<br><b>${pct(withXg,results.length)}</b></div><div class="box">Con cierre<br><b>${pct(withClose,bets.length)}</b></div><div class="box">Bajas completas<br><b>${pct(withAbs,matches.length)}</b></div><div class="box">Fuerza rivales<br><b>${pct(withOpp,matches.length)}</b></div></div>`;const note=document.getElementById('histBackupNote');if(note)note.textContent=`Último backup histórico: ${last?new Date(last).toLocaleString('es-CO'):'nunca'}${matches.length>=100&&!last?' · ⚠️ Conviene exportar un JSON completo.':''}`;}
function pager(total){const pages=Math.max(1,Math.ceil(total/HCFG.pageSize));state.page=Math.min(state.page,pages);const el=document.getElementById('histPager');if(!el)return;el.innerHTML=`<button type="button" class="secondary" ${state.page<=1?'disabled':''} id="hpPrev">←</button><span>Página ${state.page} / ${pages} · ${total} registro(s)</span><button type="button" class="secondary" ${state.page>=pages?'disabled':''} id="hpNext">→</button>`;document.getElementById('hpPrev')?.addEventListener('click',()=>{state.page--;renderHistorical()});document.getElementById('hpNext')?.addEventListener('click',()=>{state.page++;renderHistorical()});}
function tableMatches(items,bets,results){const rm=new Map(results.map(r=>[r.matchId,r]));return `<div class="table-scroll historical-table"><table><tr><th>Match ID</th><th>Fecha</th><th>Liga</th><th>Modo</th><th>Partido</th><th>Nivel L/V</th><th>λ L/V</th><th>λ Total</th><th>Top Pick</th><th>P</th><th>Cuota</th><th>EV</th><th>EV peor</th><th>Rob.</th><th>Conf.</th><th>Score</th><th>Stake sug.</th><th>Resultado</th><th>P&L</th><th>Decisión</th><th>Model Version</th></tr>${items.map(x=>{const rr=rm.get(x.matchId),pnl=bets.filter(b=>b.matchId===x.matchId&&b.status!=='pending').reduce((s,b)=>s+(n(b.pnl,0)||0),0);return `<tr data-match="${esc(x.matchId)}"><td><b>${esc(x.matchId)}</b></td><td>${esc(x.date)}</td><td>${esc(x.league)}</td><td>${x.mode==='cup'?'Copa':'Liga'}</td><td>${esc(x.home)} vs ${esc(x.away)}</td><td>${fmtNum(x.levelHome,0)} / ${fmtNum(x.levelAway,0)}</td><td>${fmtNum(x.lambdaHome)} / ${fmtNum(x.lambdaAway)}</td><td>${fmtNum(x.lambdaTotal)}</td><td>${esc(x.topPick)}</td><td>${fmtPct(x.probability)}</td><td>${fmtNum(x.oddsAvailable)}</td><td>${fmtPct(x.ev)}</td><td>${fmtPct(x.worstEV)}</td><td>${fmtNum(x.robustness,0)}</td><td>${fmtNum(x.confidence,0)}</td><td>${fmtNum(x.score,0)}</td><td>${fmtPct(x.suggestedStakePct)}</td><td>${rr?`${fmtNum(rr.homeGoals,0)}-${fmtNum(rr.awayGoals,0)}`:'—'}</td><td>${fmtMoney(pnl)}</td><td>${esc(x.topDecision)}</td><td>${esc(x.modelVersion)}</td></tr>`}).join('')}</table></div>`;}
function tableBets(items){return `<div class="table-scroll historical-table"><table><tr><th>Bet ID</th><th>Match ID</th><th>Fecha</th><th>Liga</th><th>Partido</th><th>Mercado</th><th>Selección</th><th>Cuota tomada</th><th>P modelo</th><th>P fair mercado</th><th>EV</th><th>EV peor</th><th>Rob.</th><th>Conf.</th><th>Score</th><th>Stake</th><th>Resultado</th><th>P&L</th><th>Cierre</th><th>CLV</th><th>Brier</th><th>Build</th></tr>${items.map(x=>`<tr data-bet="${esc(x.betId)}"><td><b>${esc(x.betId)}</b></td><td>${esc(x.matchId)}</td><td>${esc(x.date)}</td><td>${esc(x.league)}</td><td>${esc(x.match)}</td><td>${esc(typeof marketLabel==='function'?marketLabel(x.market):x.market)}</td><td>${esc(x.selection)}</td><td>${fmtNum(x.oddsTaken)}</td><td>${fmtPct(x.modelProbability)}</td><td>${fmtPct(x.marketFairProbability)}</td><td>${fmtPct(x.ev)}</td><td>${fmtPct(x.worstEV)}</td><td>${fmtNum(x.robustness,0)}</td><td>${fmtNum(x.confidence,0)}</td><td>${fmtNum(x.score,0)}</td><td>${fmtMoney(x.stakeAmount)}</td><td>${statusEs(x.status)}</td><td>${fmtMoney(x.pnl)}</td><td>${fmtNum(x.closingOdds)}</td><td>${fmtPct(x.clv)}</td><td>${fmtNum(x.brier,3)}</td><td>${esc(x.modelVersion)}</td></tr>`).join('')}</table></div>`;}
function tableResults(items,matches){const mm=new Map(matches.map(x=>[x.matchId,x]));return `<div class="table-scroll historical-table"><table><tr><th>Match ID</th><th>Partido</th><th>Marcador</th><th>Total</th><th>xG real</th><th>Error λ L</th><th>Error λ V</th><th>Error λ Total</th><th>Registrado</th></tr>${items.map(x=>{const m=mm.get(x.matchId);return `<tr data-result="${esc(x.matchId)}"><td><b>${esc(x.matchId)}</b></td><td>${esc(m?`${m.home} vs ${m.away}`:'—')}</td><td>${fmtNum(x.homeGoals,0)} - ${fmtNum(x.awayGoals,0)}</td><td>${fmtNum(x.totalGoals,0)}</td><td>${fmtNum(x.homeXg)} / ${fmtNum(x.awayXg)}</td><td>${fmtNum(x.lambdaErrorHome)}</td><td>${fmtNum(x.lambdaErrorAway)}</td><td>${fmtNum(x.lambdaErrorTotal)}</td><td>${esc(x.recordedAt?new Date(x.recordedAt).toLocaleString('es-CO'):'—')}</td></tr>`}).join('')}</table></div>`;}
function buildRows(matches,bets,results){const bm=new Map();matches.forEach(m=>{const k=m.modelVersion||'Legacy';if(!bm.has(k))bm.set(k,{k,m:[],b:[],r:[]});bm.get(k).m.push(m)});bets.forEach(b=>{const k=b.modelVersion||'Legacy';if(!bm.has(k))bm.set(k,{k,m:[],b:[],r:[]});bm.get(k).b.push(b)});const matchBuild=new Map(matches.map(m=>[m.matchId,m.modelVersion||'Legacy']));results.forEach(r=>{const k=matchBuild.get(r.matchId)||'Legacy';if(!bm.has(k))bm.set(k,{k,m:[],b:[],r:[]});bm.get(k).r.push(r)});return [...bm.values()].map(g=>{const dec=g.b.filter(x=>['win','loss'].includes(x.status)),cash=g.b.filter(x=>!x.isFreeBet&&x.status!=='pending'),stake=cash.reduce((s,x)=>s+(n(x.stakeAmount,0)||0),0),pnl=cash.reduce((s,x)=>s+(n(x.pnl,0)||0),0);return {build:g.k,n:g.m.length,bets:g.b.length,roi:stake?pnl/stake:null,brier:avgN(dec.map(x=>x.brier)),clv:avgN(g.b.map(x=>x.clv)),maeH:avgN(g.r.map(x=>x.lambdaErrorHome==null?null:Math.abs(x.lambdaErrorHome))),maeA:avgN(g.r.map(x=>x.lambdaErrorAway==null?null:Math.abs(x.lambdaErrorAway))),maeT:avgN(g.r.map(x=>x.lambdaErrorTotal==null?null:Math.abs(x.lambdaErrorTotal))),rmse:rmse(g.r.map(x=>x.lambdaErrorTotal)),winRate:dec.length?dec.filter(x=>x.status==='win').length/dec.length:null};});}
const rmse=a=>{const v=a.map(n).filter(Number.isFinite);return v.length?Math.sqrt(v.reduce((s,x)=>s+x*x,0)/v.length):null};
function tableBuilds(rows){return `<div class="table-scroll historical-table"><table><tr><th>Build</th><th>Partidos</th><th>Apuestas</th><th>Win Rate</th><th>ROI</th><th>Brier</th><th>CLV</th><th>MAE λ L</th><th>MAE λ V</th><th>MAE total</th><th>RMSE total</th></tr>${rows.map(x=>`<tr><td><b>${esc(x.build)}</b></td><td>${x.n}</td><td>${x.bets}</td><td>${fmtPct(x.winRate)}</td><td>${fmtPct(x.roi)}</td><td>${fmtNum(x.brier,3)}</td><td>${fmtPct(x.clv)}</td><td>${fmtNum(x.maeH)}</td><td>${fmtNum(x.maeA)}</td><td>${fmtNum(x.maeT)}</td><td>${fmtNum(x.rmse)}</td></tr>`).join('')}</table></div><p class="small muted">Comparar builds por calibración/Brier/error λ/CLV además de ROI. Una muestra pequeña no prueba superioridad.</p>`;}
function renderSummary(s){const el=document.getElementById('histFilteredSummary');if(!el)return;el.innerHTML=`<div class="summary hist-filter-summary"><div class="box">N apuestas<br><b>${s.n}</b></div><div class="box">Win Rate<br><b>${fmtPct(s.winRate)}</b></div><div class="box">ROI<br><b>${fmtPct(s.roi)}</b></div><div class="box">P&L<br><b>${fmtMoney(s.pnl)}</b></div><div class="box">P media<br><b>${fmtPct(s.pred)}</b></div><div class="box">EV medio<br><b>${fmtPct(s.ev)}</b></div><div class="box">EV peor<br><b>${fmtPct(s.worst)}</b></div><div class="box">Rob. media<br><b>${fmtNum(s.rob,1)}</b></div><div class="box">Brier<br><b>${fmtNum(s.brier,3)}</b></div><div class="box">CLV medio<br><b>${fmtPct(s.clv)}</b></div><div class="box">Profit Factor<br><b>${fmtNum(s.pf,2)}</b></div></div>`;}
async function renderHistorical(){await syncAll();const [matches,bets,results]=await Promise.all([idbAll(HCFG.matchStore),idbAll(HCFG.betStore),idbAll(HCFG.resultStore)]);filterPanelOptions(matches,bets);await health(matches,bets,results);renderSummary(statsFiltered(matches,bets,results));const table=document.getElementById('histTable');if(!table)return;let data=[];
  if(state.view==='matches'){data=matches.filter(x=>pass(x,'matches')).sort((a,b)=>String(b.analyzedAt||b.date).localeCompare(String(a.analyzedAt||a.date)));}else if(state.view==='bets'){data=bets.filter(x=>pass(x,'bets')).sort((a,b)=>String(b.betRegisteredAt||b.date).localeCompare(String(a.betRegisteredAt||a.date)));}else if(state.view==='results'){data=results.filter(x=>{const m=matches.find(y=>y.matchId===x.matchId);return !m||pass(m,'matches')}).sort((a,b)=>String(b.recordedAt).localeCompare(String(a.recordedAt)));}else{table.innerHTML=tableBuilds(buildRows(matches,bets,results));pager(0);return;}
  pager(data.length);const slice=data.slice((state.page-1)*HCFG.pageSize,state.page*HCFG.pageSize);table.innerHTML=state.view==='matches'?tableMatches(slice,bets,results):state.view==='bets'?tableBets(slice):tableResults(slice,matches);table.querySelectorAll('[data-match]').forEach(tr=>tr.onclick=()=>openMatchSheet(tr.dataset.match));table.querySelectorAll('[data-bet]').forEach(tr=>tr.onclick=()=>openBetSheet(tr.dataset.bet));table.querySelectorAll('[data-result]').forEach(tr=>tr.onclick=()=>openResultSheet(tr.dataset.result));}
window.renderHistoricalBase=renderHistorical;

function modal(title,body){const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-backdrop"></div><div class="modal-sheet hist-sheet"><div class="modal-head"><div><div class="eyebrow">BASE HISTÓRICA</div><h2>${esc(title)}</h2></div><button class="icon-btn secondary" type="button">✕</button></div>${body}</div>`;document.body.appendChild(m);const close=()=>m.remove();m.querySelector('.modal-backdrop').onclick=close;m.querySelector('.icon-btn').onclick=close;return m;}
function block(title,obj){return `<details class="hist-details" open><summary>${esc(title)}</summary><pre>${esc(JSON.stringify(obj,null,2))}</pre></details>`}
async function openMatchSheet(id){const [m,bets,r]=await Promise.all([idbGet(HCFG.matchStore,id),idbAll(HCFG.betStore),idbGet(HCFG.resultStore,id)]);if(!m)return;modal(`${m.home} vs ${m.away}`,`<div class="note"><b>${esc(m.matchId)}</b> · ${esc(m.modelVersion)} · ${esc(m.status)}</div>${block('Identificación',{matchId:m.matchId,date:m.date,time:m.time,league:m.league,country:m.country,competition:m.competition,mode:m.mode,round:m.round,home:m.home,away:m.away,modelVersion:m.modelVersion,analyzedAt:m.analyzedAt})}${block('ANTES DEL PARTIDO · Snapshot inmutable',m.preMatchSnapshot)}${block('Apuestas relacionadas',bets.filter(x=>x.matchId===id))}${block('DESPUÉS DEL PARTIDO · Resultado real',r||{dato:null})}`);}
async function openBetSheet(id){const b=await idbGet(HCFG.betStore,id);if(!b)return;const m=modal(`${b.selection||b.market} · ${b.match}`,`<div class="note"><b>${esc(b.betId)}</b> → ${esc(b.matchId)}</div><div class="actions"><button type="button" id="histEditClosing">Editar cuota cierre</button><button type="button" class="secondary" id="histEditNotes">Editar notas</button></div>${block('Apuesta',b)}${block('Snapshot prepartido congelado',b.preMatchSnapshot||{dato:null})}`);m.querySelector('#histEditClosing').onclick=()=>editClosingOdds(b);m.querySelector('#histEditNotes').onclick=()=>editBetNotes(b);}
async function openResultSheet(id){const r=await idbGet(HCFG.resultStore,id);if(!r)return;modal(`Resultado ${id}`,`${block('DESPUÉS DEL PARTIDO',r)}<p class="small muted">Los datos postpartido nunca se escriben dentro del snapshot prepartido.</p>`);}
function auditChange(obj,field,oldValue,newValue){obj.auditLog=obj.auditLog||[];obj.auditLog.push({field,oldValue,newValue,changedAt:iso()});obj.updatedAt=iso();}
async function editClosingOdds(hb){const raw=prompt('Cuota de cierre (vacío = sin dato):',hb.closingOdds??'');if(raw===null)return;const nv=raw.trim()===''?null:n(raw);if(nv!==null&&nv<=1)return alert('Cuota de cierre inválida.');const bets=loadBets(),b=bets.find(x=>x.betId===hb.betId||String(x.id)===String(hb.legacyBetId));if(!b)return alert('No se encontró la apuesta original.');auditChange(b,'closingOdds',b.closingOdds??null,nv);b.closingOdds=nv;b.clv=nv!=null?n(b.odds)/nv-1:null;saveBets(bets);await syncAll();renderHistorical();document.querySelectorAll('.modal').forEach(x=>x.remove());}
async function editBetNotes(hb){const raw=prompt('Notas de la apuesta:',hb.notes||'');if(raw===null)return;const bets=loadBets(),b=bets.find(x=>x.betId===hb.betId||String(x.id)===String(hb.legacyBetId));if(!b)return;auditChange(b,'notes',b.notes||null,raw);b.notes=raw;saveBets(bets);await syncAll();renderHistorical();document.querySelectorAll('.modal').forEach(x=>x.remove());}

function csvCell(v){if(v==null)return '';const s=typeof v==='object'?JSON.stringify(v):String(v);return `"${s.replace(/"/g,'""')}"`}
function download(name,text,type='text/csv;charset=utf-8'){const blob=new Blob(['\ufeff'+text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
function toCSV(rows,cols){return [cols.join(','),...rows.map(r=>cols.map(c=>csvCell(r[c])).join(','))].join('\r\n')}
async function exportKind(kind){await syncAll();const [matches,bets,results]=await Promise.all([idbAll(HCFG.matchStore),idbAll(HCFG.betStore),idbAll(HCFG.resultStore)]);const now=new Date(),stamp=`${now.getFullYear()}${String(now.getMonth()+1).padStart(2,'0')}${String(now.getDate()).padStart(2,'0')}`;if(kind==='json'){const meta={schemaVersion:HCFG.schemaVersion,exportedAt:iso(),modelBuild:2500};download(`SoyJordan_Base_Historica_${stamp}.json`,JSON.stringify({meta,matches,bets,results},null,2),'application/json;charset=utf-8');await metaSet('lastBackupAt',iso());return renderHistorical();}const rows=kind==='matches'?matches:kind==='bets'?bets:results;const cols=kind==='matches'?['matchId','date','league','country','competition','mode','home','away','levelHome','levelAway','lambdaHome','lambdaAway','lambdaTotal','topPick','topMarket','topDecision','probability','oddsAvailable','ev','worstEV','robustness','confidence','score','suggestedStakePct','noBetReason','modelVersion','createdAt','analyzedAt','lockedAt','status']:kind==='bets'?['betId','matchId','date','league','match','market','selection','oddsAvailable','oddsSelected','oddsTaken','closingOdds','modelProbability','marketFairProbability','edge','ev','worstEV','robustness','confidence','score','stakePct','stakeAmount','isFreeBet','status','pnl','clv','brier','modelVersion','betRegisteredAt','settledAt']:['matchId','homeGoals','awayGoals','totalGoals','homeXg','awayXg','homeShots','awayShots','homeSot','awaySot','homeBigChances','awayBigChances','lambdaErrorHome','lambdaErrorAway','lambdaErrorTotal','recordedAt','settledAt'];download(`SoyJordan_${kind}_${stamp}.csv`,toCSV(rows,cols));}
function showExportMenu(){const m=modal('Exportar Base Histórica',`<div class="hist-export-grid"><button data-ex="matches">Partidos CSV</button><button data-ex="bets">Apuestas CSV</button><button data-ex="results">Resultados CSV</button><button data-ex="json">Base completa JSON</button></div><p class="small muted">CSV incluye BOM UTF-8 y encabezados estables para abrir correctamente en Excel.</p>`);m.querySelectorAll('[data-ex]').forEach(b=>b.onclick=()=>exportKind(b.dataset.ex));}

// Import extension: historical JSON can be imported from the Datos screen without replacing legacy flow.
window.importHistoricalJSON=async function(obj){if(!obj||!Array.isArray(obj.matches)||!Array.isArray(obj.bets)||!Array.isArray(obj.results))throw new Error('Formato histórico inválido');await Promise.all([idbPutMany(HCFG.matchStore,obj.matches),idbPutMany(HCFG.betStore,obj.bets),idbPutMany(HCFG.resultStore,obj.results)]);await metaSet('lastImportedAt',iso());return {matches:obj.matches.length,bets:obj.bets.length,results:obj.results.length};};

// Explicit bias-safe reliability helper: only records strictly prior to timestamp.
window.historicalMarketReliabilityBefore=async function(market,beforeIso){const all=await idbAll(HCFG.betStore),rows=all.filter(x=>x.market===market&&x.betRegisteredAt&&x.betRegisteredAt<beforeIso&&['win','loss'].includes(x.status));return {n:rows.length,winRate:rows.length?rows.filter(x=>x.status==='win').length/rows.length:null,roi:(()=>{const c=rows.filter(x=>!x.isFreeBet),s=c.reduce((a,x)=>a+(n(x.stakeAmount,0)||0),0),p=c.reduce((a,x)=>a+(n(x.pnl,0)||0),0);return s?p/s:null})(),brier:avgN(rows.map(x=>x.brier)),clv:avgN(rows.map(x=>x.clv))};};


// Extend post-match audit with optional real match statistics without touching pre-match inputs.
function injectAuditRealFields(){const modal=document.getElementById('auditResultModal');if(!modal||document.getElementById('auditHomeShots'))return;const notes=document.getElementById('auditNotes')?.closest('label');if(!notes)return;const box=document.createElement('div');box.className='grid';box.innerHTML=`
<label>Tiros reales LOCAL <span class="muted">(opcional)</span><input id="auditHomeShots" type="number" min="0" step="1"></label><label>Tiros reales VISITANTE <span class="muted">(opcional)</span><input id="auditAwayShots" type="number" min="0" step="1"></label>
<label>SOT reales LOCAL <span class="muted">(opcional)</span><input id="auditHomeSot" type="number" min="0" step="1"></label><label>SOT reales VISITANTE <span class="muted">(opcional)</span><input id="auditAwaySot" type="number" min="0" step="1"></label>
<label>Ocasiones claras LOCAL <span class="muted">(opcional)</span><input id="auditHomeBC" type="number" min="0" step="1"></label><label>Ocasiones claras VISITANTE <span class="muted">(opcional)</span><input id="auditAwayBC" type="number" min="0" step="1"></label>`;notes.parentNode.insertBefore(box,notes);}
const _openAuditModal=window.openAuditModal;window.openAuditModal=function(id){_openAuditModal(id);injectAuditRealFields();const r=loadDB().find(x=>String(x.id)===String(id)),rr=r?.realResult||{};[['auditHomeShots','homeShots'],['auditAwayShots','awayShots'],['auditHomeSot','homeSot'],['auditAwaySot','awaySot'],['auditHomeBC','homeBigChances'],['auditAwayBC','awayBigChances']].forEach(([el,k])=>{const x=document.getElementById(el);if(x)x.value=rr[k]??''});};
const _saveRealResult=window.saveRealResult;window.saveRealResult=function(){const analysisId=window.auditAnalysisId??(typeof auditAnalysisId!=='undefined'?auditAnalysisId:null);const extra={};[['auditHomeShots','homeShots'],['auditAwayShots','awayShots'],['auditHomeSot','homeSot'],['auditAwaySot','awaySot'],['auditHomeBC','homeBigChances'],['auditAwayBC','awayBigChances']].forEach(([el,k])=>{const raw=document.getElementById(el)?.value;extra[k]=raw==null||String(raw).trim()===''?null:Number(raw)});_saveRealResult();const db=loadDB();let r=analysisId!=null?db.find(x=>String(x.id)===String(analysisId)):db.find(x=>x.realResult&&x.realResult.recordedAt);if(r?.realResult){Object.assign(r.realResult,extra);r.updatedAt=iso();saveDB(db);setTimeout(()=>{syncAll();window.renderHistoricalBase?.();},0);}};

// Main backup V2.5 now includes the complete historical stores. Older backups remain importable.
window.exportData=async function(){await syncAll();const [matches,betsHist,results]=await Promise.all([idbAll(HCFG.matchStore),idbAll(HCFG.betStore),idbAll(HCFG.resultStore)]);const payload={format:'SoyJordan Picks Backup',version:'2.5.0',build:2500,exportedAt:iso(),analyses:loadDB(),bets:loadBets(),combos:loadCombos(),bank:loadBank(),historical:{schemaVersion:HCFG.schemaVersion,matches,bets:betsHist,results}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='SoyJordan_Picks_V2_5_0_build2500_Backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);await metaSet('lastBackupAt',iso());const msg=document.getElementById('dataMsg');if(msg)msg.textContent='Backup V2.5 completo exportado, incluida Base Histórica.';window.renderHistoricalBase?.();};
window.importData=function(e){const f=e.target.files?.[0];if(!f)return;const rd=new FileReader();rd.onload=async()=>{try{const incoming=JSON.parse(rd.result),analyses=Array.isArray(incoming)?incoming:(incoming.analyses||[]);if(!Array.isArray(analyses))throw Error('Formato no válido');const current=loadDB(),byId=new Map(current.map(x=>[String(x.id),x]));analyses.forEach(x=>{if(x?.id!=null)byId.set(String(x.id),x)});saveDB([...byId.values()].sort((a,b)=>(Number(b.id)||0)-(Number(a.id)||0)));if(!Array.isArray(incoming)){if(Array.isArray(incoming.bets)){const m=new Map(loadBets().map(x=>[String(x.id),x]));incoming.bets.forEach(x=>x?.id!=null&&m.set(String(x.id),x));saveBets([...m.values()])}if(Array.isArray(incoming.combos)){const m=new Map(loadCombos().map(x=>[String(x.id),x]));incoming.combos.forEach(x=>x?.id!=null&&m.set(String(x.id),x));saveCombos([...m.values()])}if(incoming.bank&&typeof incoming.bank==='object')saveBank(incoming.bank);if(incoming.historical?.matches){await window.importHistoricalJSON(incoming.historical);}}await syncAll();const msg=document.getElementById('dataMsg');if(msg)msg.textContent=`Backup importado. Análisis: ${loadDB().length} · Apuestas: ${loadBets().length} · Base Histórica sincronizada.`;if(document.getElementById('importFile'))document.getElementById('importFile').value='';renderBank();show('history');}catch(err){console.error(err);const msg=document.getElementById('dataMsg');if(msg)msg.textContent='Archivo no válido o importación incompleta.';if(document.getElementById('importFile'))document.getElementById('importFile').value='';}};rd.readAsText(f);};

// Repaint Historical Base after settlement/calibration flows without requiring a PWA reload.
const _renderCalibration=window.renderCalibration;window.renderCalibration=function(){_renderCalibration();if(!document.getElementById('historicalBase')?.classList.contains('hidden'))setTimeout(renderHistorical,0);};

if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{injectUI();injectAuditRealFields();syncAll();});else{injectUI();injectAuditRealFields();syncAll();}
})();
